BASE: ['']
TOOLBOX_MODE: "train_and_test"  # "train_and_test" or "only_train" or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 5
  LR: 1e-4
  MODEL_FILE_NAME: SCAMPS_SCAMPS_MMRPhysLEF_BVP_RSP_RGBx160x72_SFSAM_Label
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 30
    DATASET: SCAMPS
    DO_PREPROCESS: False            # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/mnt/sda/data/raw/SCAMPS/scamps_videos"          # Raw dataset path, need to be updated
    CACHED_PATH: "/mnt/sdc1/rppg/SCAMPS"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: "SCAMPS_Raw_160_72x72"
    BEGIN: 0.0
    END: 0.8
    PREPROCESS:
      DATA_TYPE: ['Raw']         #if use MMRPhys, should be Raw
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'Y5F'    # HC for Haar Cascade, RF for RetinaFace, Y5F for YOLO5Face
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
VALID:
  DATA:
    FS: 30
    DATASET: SCAMPS
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/mnt/sda/data/raw/SCAMPS/scamps_videos"          # Raw dataset path, need to be updated
    CACHED_PATH: "/mnt/sdc1/rppg/SCAMPS"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: "SCAMPS_Raw_160_72x72"
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Raw']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'Y5F'    # HC for Haar Cascade, RF for RetinaFace, Y5F for YOLO5Face
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'MACC', 'Pearson', 'SNR', 'BA']
  USE_LAST_EPOCH: True                   # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 30
    DATASET: SCAMPS
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/mnt/sda/data/raw/SCAMPS/scamps_videos"          # Raw dataset path, need to be updated
    CACHED_PATH: "/mnt/sdc1/rppg/SCAMPS"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: "SCAMPS_Raw_160_72x72"
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Raw']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'Y5F'    # HC for Haar Cascade, RF for RetinaFace, Y5F for YOLO5Face
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.1
  NAME: MMRPhys
  MMRPhys:
    CHANNELS: 3
    FRAME_NUM: 160
    TYPE: "LEF"
    TASKS: ["BVP", "RSP"]
    MD_FSAM: True
    MD_TYPE: "SNMF_Label"
    MD_R: 1
    MD_S: 1
    MD_STEPS: 3
    MD_RESIDUAL: True
    MD_INFERENCE: False
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 30        # In seconds
  MODEL_PATH: ""