BASE: ['']
TOOLBOX_MODE: "train_and_test"  # "train_and_test" or "only_train" or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 10
  LR: 1e-3
  MODEL_FILE_NAME: BP4D_MMRPhysLEF_BP_RGBx72_Base_Fold1
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 25
    DATASET: BP4D
    DO_PREPROCESS: False            # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/mnt/sda/data/raw/BP4D_72x72"          # Raw dataset path, need to be updated
    CACHED_PATH: "/mnt/sdc1/rppg/BP4D"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: "BP4D_RGBT_500_72x72"
    FOLD:
      FOLD_NAME: 'Fold1_Train'
      FOLD_PATH: './dataset/BP4D_BigSmall_Subject_Splits/Split1_Train_Subjects.csv'
    PREPROCESS:
      PREPROCESS_FRAMES: True
      DATA_TYPE: ['Raw']         #if use MMRPhys, should be Raw
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 500
      CROP_FACE:
        DO_CROP_FACE: False
        BACKEND: 'Y5F'    # HC for Haar Cascade, RF for RetinaFace, Y5F for YOLO5Face
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY : 25
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      BP4D:
        DATA_MODE: RGBT
      RESIZE:
        H: 72
        W: 72
VALID:
  DATA:
    FS: 25
    DATASET: BP4D
    DO_PREPROCESS: False            # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/mnt/sda/data/raw/BP4D_72x72"          # Raw dataset path, need to be updated
    CACHED_PATH: "/mnt/sdc1/rppg/BP4D"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: "BP4D_RGBT_500_72x72"
    FOLD:
      FOLD_NAME: 'Fold1_Test'
      FOLD_PATH: './dataset/BP4D_BigSmall_Subject_Splits/Split1_Test_Subjects.csv'
    PREPROCESS:
      PREPROCESS_FRAMES: True
      DATA_TYPE: ['Raw']         #if use MMRPhys, should be Raw
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 500
      CROP_FACE:
        DO_CROP_FACE: False
        BACKEND: 'Y5F'    # HC for Haar Cascade, RF for RetinaFace, Y5F for YOLO5Face
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY : 25
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      BP4D:
        DATA_MODE: RGBT
      RESIZE:
        H: 72
        W: 72
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA', 'MACC']
  USE_LAST_EPOCH: True                   # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 25
    DATASET: BP4D
    DO_PREPROCESS: False            # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/mnt/sda/data/raw/BP4D_72x72"          # Raw dataset path, need to be updated
    CACHED_PATH: "/mnt/sdc1/rppg/BP4D"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: "BP4D_RGBT_500_72x72"
    FOLD:
      FOLD_NAME: 'Fold1_Test'
      FOLD_PATH: './dataset/BP4D_BigSmall_Subject_Splits/Split1_Test_Subjects.csv'
    PREPROCESS:
      PREPROCESS_FRAMES: True
      DATA_TYPE: ['Raw']         #if use MMRPhys, should be Raw
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 500
      CROP_FACE:
        DO_CROP_FACE: False
        BACKEND: 'Y5F'    # HC for Haar Cascade, RF for RetinaFace, Y5F for YOLO5Face
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY : 25
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      BP4D:
        DATA_MODE: RGBT
      RESIZE:
        H: 72
        W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.1
  NAME: MMRPhys
  MMRPhys:
    CHANNELS: 3
    FRAME_NUM: 500
    TYPE: "LEF"
    TASKS: ["BP"]
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 30        # In seconds
  MODEL_PATH: ""